# Generated by Django 6.0.5 on 2026-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crop', models.CharField(choices=[('maize', 'Maize'), ('beans', 'Beans'), ('tomatoes', 'Tomatoes'), ('potatoes', 'Potatoes'), ('wheat', 'Wheat'), ('sorghum', 'Sorghum'), ('cassava', 'Cassava'), ('sweet_potato', 'Sweet Potato'), ('kale', 'Kale (Sukuma Wiki)'), ('cabbage', 'Cabbage')], max_length=50)),
                ('soil_type', models.CharField(choices=[('loam', 'Loam'), ('clay', 'Clay'), ('sandy', 'Sandy'), ('silty', 'Silty'), ('peaty', 'Peaty')], max_length=50)),
                ('season', models.CharField(choices=[('long_rains', 'Long Rains (Mar–May)'), ('short_rains', 'Short Rains (Oct–Dec)'), ('dry', 'Dry Season (Irrigation)')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_notes', models.TextField(blank=True)),
                ('planting_schedule', models.TextField(blank=True)),
                ('input_requirements', models.TextField(blank=True)),
                ('weather_risks', models.TextField(blank=True)),
                ('purchase_orders', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
